const WORLD_MAP_SERIES = "WORLD_MAP_SERIES";
const USA_MAP_SERIES = "USA_MAP_SERIES";
const INDIA_MAP_SERIES = "INDIA_MAP_SERIES";

export default {
    WORLD_MAP_SERIES,
    USA_MAP_SERIES,
    INDIA_MAP_SERIES
}