const WORLD_MAP_SERIES = "WORLD_MAP_SERIES";
const USA_MAP_SERIES = "USA_MAP_SERIES";
const INDIA_MAP_SERIES = "INDIA_MAP_SERIES";
const DRILL_DOWN_WORLD_SERIES = "DRILL_DOWN_WORLD_SERIES";
const IMAGE_SERIES = "IMAGE_SERIES";
const DRILL_DOWN_COUNTRY_SERIES = "DRILL_DOWN_COUNTRY_SERIES";


export default {
    WORLD_MAP_SERIES,
    USA_MAP_SERIES,
    INDIA_MAP_SERIES,
    DRILL_DOWN_WORLD_SERIES,
    IMAGE_SERIES,
    DRILL_DOWN_COUNTRY_SERIES
}