// Charts
const COLUMN_SERIES_CHART = "COLUMN_SERIES_CHART";
const STACKED_COLUMN_SERIES_CHART = "STACKED_COLUMN_SERIES_CHART";
const PIE_CHART = "PIE_CHART";

export default {
    COLUMN_SERIES_CHART,
    STACKED_COLUMN_SERIES_CHART,
    PIE_CHART
}





