// Series

const COLUMN_SERIES = "COLUMN_SERIES";
const STACKED_COLUMN_SERIES = "STACKED_COLUMN_SERIES";
const PIE_SERIES = "PIE_SERIES";


export default {
    COLUMN_SERIES,
    STACKED_COLUMN_SERIES,
    PIE_SERIES
}